app:
  telegram-token: 6387539887:AAE-5BaNwisrDtY5ZiZZthsSY_RlHWkY_vI
  back-off: constant
  retry-codes: 500, 400, 404

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc.swagger-ui.path: /swagger-ui
